# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protoc import collect_face_pb2 as collect__face__pb2


class CollectFaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DoCollectFace = channel.unary_unary(
        '/collect_face.CollectFace/DoCollectFace',
        request_serializer=collect__face__pb2.CollectFaceRequest.SerializeToString,
        response_deserializer=collect__face__pb2.CollectFaceResponse.FromString,
        )


class CollectFaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DoCollectFace(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CollectFaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DoCollectFace': grpc.unary_unary_rpc_method_handler(
          servicer.DoCollectFace,
          request_deserializer=collect__face__pb2.CollectFaceRequest.FromString,
          response_serializer=collect__face__pb2.CollectFaceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'collect_face.CollectFace', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
