# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collect_face.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collect_face.proto',
  package='collect_face',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63ollect_face.proto\x12\x0c\x63ollect_face\"G\n\x05Image\x12\x10\n\x08raw_data\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0c\n\x04high\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"&\n\x12\x43ollectFaceRequest\x12\x10\n\x08staff_id\x18\x01 \x01(\x05\"K\n\x13\x43ollectFaceResponse\x12\x10\n\x08staff_id\x18\x01 \x01(\x05\x12\"\n\x05image\x18\x02 \x01(\x0b\x32\x13.collect_face.Image2e\n\x0b\x43ollectFace\x12V\n\rDoCollectFace\x12 .collect_face.CollectFaceRequest\x1a!.collect_face.CollectFaceResponse\"\x00\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='collect_face.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_data', full_name='collect_face.Image.raw_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='collect_face.Image.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='collect_face.Image.high', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channel', full_name='collect_face.Image.channel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=107,
)


_COLLECTFACEREQUEST = _descriptor.Descriptor(
  name='CollectFaceRequest',
  full_name='collect_face.CollectFaceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='staff_id', full_name='collect_face.CollectFaceRequest.staff_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=147,
)


_COLLECTFACERESPONSE = _descriptor.Descriptor(
  name='CollectFaceResponse',
  full_name='collect_face.CollectFaceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='staff_id', full_name='collect_face.CollectFaceResponse.staff_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='collect_face.CollectFaceResponse.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=224,
)

_COLLECTFACERESPONSE.fields_by_name['image'].message_type = _IMAGE
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['CollectFaceRequest'] = _COLLECTFACEREQUEST
DESCRIPTOR.message_types_by_name['CollectFaceResponse'] = _COLLECTFACERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'collect_face_pb2'
  # @@protoc_insertion_point(class_scope:collect_face.Image)
  ))
_sym_db.RegisterMessage(Image)

CollectFaceRequest = _reflection.GeneratedProtocolMessageType('CollectFaceRequest', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTFACEREQUEST,
  __module__ = 'collect_face_pb2'
  # @@protoc_insertion_point(class_scope:collect_face.CollectFaceRequest)
  ))
_sym_db.RegisterMessage(CollectFaceRequest)

CollectFaceResponse = _reflection.GeneratedProtocolMessageType('CollectFaceResponse', (_message.Message,), dict(
  DESCRIPTOR = _COLLECTFACERESPONSE,
  __module__ = 'collect_face_pb2'
  # @@protoc_insertion_point(class_scope:collect_face.CollectFaceResponse)
  ))
_sym_db.RegisterMessage(CollectFaceResponse)



_COLLECTFACE = _descriptor.ServiceDescriptor(
  name='CollectFace',
  full_name='collect_face.CollectFace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=226,
  serialized_end=327,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoCollectFace',
    full_name='collect_face.CollectFace.DoCollectFace',
    index=0,
    containing_service=None,
    input_type=_COLLECTFACEREQUEST,
    output_type=_COLLECTFACERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COLLECTFACE)

DESCRIPTOR.services_by_name['CollectFace'] = _COLLECTFACE

# @@protoc_insertion_point(module_scope)
